// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  wikiSidebar: [
    'intro',
    'faq',
    'misconceptions',
    {
      type: 'category',
      label: 'Foundations',
      collapsed: false,
      items: [
        'foundations/g_factor',
        'foundations/history-of-intelligence-concept',
        'foundations/discovery-of-g',
        'foundations/theories-of-g',
        'foundations/key-definitions-of-intelligence',
        'foundations/basic-statistical-terminology',
        'foundations/bifactor-and-hierarchical',
        'foundations/evolution-of-modeling-g',
        'foundations/chc-model-of-intelligence', 
      ],
    },
    {
      type: 'category',
      label: 'Landmark Intelligence Tests',
      collapsed: true,
      items: [
        'tests/stanford-binet',
        'tests/wechsler-series',
        'tests/ravens-progressive-matrices',
        'tests/woodcock-johnson',
        'tests/cattell-culture-fair',
        'tests/pre-1994-sat',
        'tests/pre-2011-gre',
        'tests/agct-army-alpha',
        'tests/asvab',
        'tests/1926-sat',
      ],
    },
    {
      type: 'category',
      label: 'Neuroscience and Genetics',
      collapsed: true,
      items: [
        'genetics/parieto-frontal-integration-theory',
        'genetics/brain-efficiency-and-neurons',
        'genetics/behavioral-genetics',
        'genetics/heritability',
        'genetics/twin-and-adoption-designs',
        'genetics/gwas-and-polygenic-scores',
      ],
    },
    {
      type: 'category',
      label: 'Influence on Society and Individuals',
      collapsed: true,
      items: [
        'influence/life-outcomes-and-success',
        'influence/academic-achievement',
        'influence/gifted-programs',
        'influence/occupations-and-specific-jobs',
        'influence/military',
      ],
    },
    {
      type: 'category',
      label: 'Statistics behind Psychometrics',
      collapsed: true,
      items: [
        'stats/reliability-and-validity',
        'stats/factor-analysis',
        'stats/item-response-theory',
        'stats/differential-item-functioning',
      ],
    },
    {
      type: 'category',
      label: 'Environment and Development',
      collapsed: true,
      items: [
        'environment/education',
        'environment/socioeconomic-status',
        'environment/nutrition',
        'environment/prenatal-and-infant-experience',
        'environment/parenting-and-resources',
        'environment/adolescence',
        'environment/aging',
      ],
    },
    {
      type: 'category',
      label: 'Neurodivergence and Psychometrics',
      collapsed: true,
      items: [
        'neurodivergence/adhd',
        'neurodivergence/autism',
        'neurodivergence/dyslexia',
        'neurodivergence/dyscalculia',
        'neurodivergence/phantasia',
        'neurodivergence/miscellaneous',
      ],
    },
    {
      type: 'category',
      label: 'Group Differences',
      collapsed: true,
      items: [
        'group-differences/race',
        'group-differences/sex',
        'group-differences/nations',
      ],
    },
    {
      type: 'category',
      label: 'Biases in Testing',
      collapsed: true,
      items: [
        'biases/practice-effect',
        'biases/spearman-law-of-diminishing-returns',
        'biases/flynn-effect',
        'biases/language-and-translation',
        'biases/measurement-invariance',
      ],
    },
    {
      type: 'category',
      label: 'Critiques of g and IQ testing',
      collapsed: true,
      items: [
        'critiques/group-differences-and-race-debates',
        'critiques/stereotype-threat-and-test-anxiety',
        'critiques/eugenics-history-and-misuse',
        'critiques/alternative-models-of-intelligence',
        'critiques/nature-vs-nurture',
      ],
    },
    {
      type: 'category',
      label: 'Miscellaneous',
      collapsed: true,
      items: [
        'misc/investment-theory',
        'misc/mensa',
        'misc/mega-test',
        'misc/liam-milliken',
      ],
    },
    'glossary',
  ],
};

export default sidebars;
